
export const ADMIN_SEARCH_LOAD_DATA = 'ADMIN_SEARCH_LOAD_DATA';

export const ADMIN_SEARCH_REQUEST_FAILED = 'ADMIN_SEARCH_REQUEST_FAILED';

export const ADMIN_LOAD_ADMIN_DATA = 'ADMIN_LOAD_ADMIN_DATA';
